# --- Text Export Fallback Functions ----------------------------------------

def create_text_fallback(report_text: str, teacher_name: str, observer_name: str, date_str: str) -> str:
    """Create a plain text version as fallback if PDF generation fails"""
    return f"""MUSIC TEACHER OBSERVATION REPORT
{date_str}

Teacher: {teacher_name if teacher_name else 'Not specified'}
Observer: {observer_name if observer_name else 'Not specified'}

{'='*80}

{report_text}

{'='*80}

Disclaimer: This observation report was generated by AI and may contain errors. Please review all content for accuracy and use professional judgment.
"""

def create_transcript_text_fallback(teacher_text: str, observer_text: str, date_str: str) -> str:
    """Create a text fallback version of the transcript export"""
    return f"""MUSIC TEACHER OBSERVATION - FULL TRANSCRIPT
{date_str}

TEACHER AUDIO:
{'='*80}

{teacher_text}

{'='*80}
OBSERVER AUDIO/NOTES:
{'='*80}

{observer_text if observer_text else "No observer audio or notes provided."}

{'='*80}
Note: This transcription was created by AI. Please verify all important information for accuracy.
"""

def create_solo_session_text_fallback(transcription: str, chat_history: list, date_str: str) -> str:
    """Create a text fallback version of the solo session export"""
    conversation_text = ""
    for msg in chat_history:
        role_label = "You: " if msg["role"] == "user" else "Coach: "
        conversation_text += f"{role_label}{msg['content']}\n\n"
    
    return f"""SOLO TEACHING REFLECTION SESSION
{date_str}

REFLECTION CONVERSATION:
{'='*80}

{conversation_text}

{'='*80}
CLASSROOM AUDIO TRANSCRIPTION:
{'='*80}

{transcription}

{'='*80}
Note: This reflection session and transcription were created by AI. Please verify all important information for accuracy.
"""
